export const tip = [
    'BatsCoding is cool',
    '@carters3421 on Scratch made the Purple Square Guy Sprite, its basically his mascot!',
    'Also check out <a style="color: lightgray;" href="https://librekitten.org/">LibreKitten</a>!',
    'BatsCoding is based off the source code of Snail IDE, which is based off the source code of PenguinMod which is based off TurboWarp, which is based off Scratch. M O D C E P T I O N.',
    'Crazy? I was crazy once. They locked me in a room, a rubber room. A rubber room with rats. And rats make me crazy.',
    "BatsCoding.",
    "I LOVE PENGUINMOD AND SNAIL IDE!!!",
    "In 2089, literally nothing will happen.",
    "Did you know? You can post your projects outside of the BatsCoding community.",
    "number 15 burger king foot lettuce",
    "thepython555 the goat",
    "Bats",
    "penguinmod:menguinpod, snail-ide:ide-snail, BatsCoding:CodsBating",
    "If the creator of BatsCoding (KotMurkot) enjoys your project, he will give you the COOL badge.",
    "Blud is reading this tip 💀💀💀",
    "Bats are cool.",
    "Maybe in another universe, bats can't fly(i guess).",
    "I just ate your soul. /j (or is it?)",
    'oh no cringe',
    'me when i wake up in the middle of the night<br/><img src="https://corsproxy.io/?https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FFZyQ8-eagAAunGr%3Fformat%3Djpg%26name%3Dmedium" width="50" height="50"/>',
    'You have lost The Game.'
];
